/**
 * SYNK-IA - Funciones del Sistema
 * © 2024 David Roldan - Chicken Palace Ibiza
 * Futuro: SYNK-IA LABS
 */

import {
  biloopAutoSync,
  revoAutoSync,
  emailAutoProcessor,
  biloopRealSync,
  revoRealSync,
  resetAndSyncReal,
  emailAutoClassifier,
  eseeCloudSync,
  generateExecutiveReport,
  intelligentAlerts,
  systemAnalytics,
  checkSecretsStatus,
  testGmailConnection,
  testRevoConnection,
  testBiloopConnection,
  biloopGetDocuments,
  biloopUploadInvoice,
  biloopDownloadPdf,
  systemFullScan,
  nvrLocalConnect,
  fullBusinessScan,
  testBiloopReal,
  smartEmailProcessor,
  processZipFile,
  processBulkPayrolls,
  clockIn,
  clockOut,
  employeeAuth,
  generateAttendanceReport,
  processFlexibleCSV,
  mergeEmployeeDuplicates,
  syncPayrollsToEmployees
} from '../services/functionsService';

export {
  biloopAutoSync,
  revoAutoSync,
  emailAutoProcessor,
  biloopRealSync,
  revoRealSync,
  resetAndSyncReal,
  emailAutoClassifier,
  eseeCloudSync,
  generateExecutiveReport,
  intelligentAlerts,
  systemAnalytics,
  checkSecretsStatus,
  testGmailConnection,
  testRevoConnection,
  testBiloopConnection,
  biloopGetDocuments,
  biloopUploadInvoice,
  biloopDownloadPdf,
  systemFullScan,
  nvrLocalConnect,
  fullBusinessScan,
  testBiloopReal,
  smartEmailProcessor,
  processZipFile,
  processBulkPayrolls,
  clockIn,
  clockOut,
  employeeAuth,
  generateAttendanceReport,
  processFlexibleCSV,
  mergeEmployeeDuplicates,
  syncPayrollsToEmployees
};
